catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('Pots', views.potFilterView.as_view(), name='Pots'),
    url('Decor', views.decorFilterView.as_view(), name='Decor'),
    url('Dishes', views.dishesFilterView.as_view(), name='Dishes'),
    url(r'^Pot/(?P<pk>\d+)$', views.potDetailView.as_view(), name='Pot-detail'),
    url(r'^Dec/(?P<pk>\d+)$', views.decDetailView.as_view(), name='Decor-detail'),
    url(r'^Dish/(?P<pk>\d+)$', views.dishDetailView.as_view(), name='Dish-detail'),
    url(r'^article/(?P<pk>\d+)$', views.articleDetailView.as_view(), name='article-detail'),
    url('Architecture', views.architectureListView.as_view(), name='Architecture'),
    url('Design', views.designListView.as_view(), name='Design'),
    url('Culture', views.cultureListView.as_view(), name='Culture'),
    url('Contacts', views.contacts, name='Contacts'),
    url('About', views.about, name='About'),
    url(r'^author/(?P<pk>\d+)$', views.authorDetailView.as_view(), name='author-detail'),
]

mashasite/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), #URL обращается к admin.site.urls
]
urlpatterns += [
     path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField

class material(models.Model):
    """
    Модель материал
    """
    name = models.CharField(max_length=20, help_text="ВВедите материал")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('material-detail', args=[str(self.id)])
    
class color(models.Model):
    """
    Модель Цвет
    """
    name = models.CharField(max_length=20, help_text="ВВедите цвет")

    def __str__(self):
        return self.name

class style(models.Model):
    """
    Модель стиль
    """
    name = models.CharField(max_length=20, help_text="ВВедите стиль")

    def __str__(self):
        return self.name

class size(models.Model):
    """
    Модель размер
    """
    name = models.CharField(max_length=20, help_text="ВВедите размер")

    def __str__(self):
        return self.name
    
class pot(models.Model):

    title = models.CharField(max_length=200)
    material = models.ForeignKey('Material', on_delete=models.SET_NULL, null=True)
    #ForeignKey потому что, один горшок имеет один материал, но из одного материала может быть множество горшков.
    summary = models.TextField(max_length=1000, help_text="Описание")
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField()
    style = models.ManyToManyField(style, help_text="Стиль")
    #ManyToMany потому что, один горшок может быть исполнен в нескольких стилях.

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('Pot-detail', args=[str(self.id)])

class dishes(models.Model):

    title = models.CharField(max_length=200)
    material = models.ForeignKey('Material', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Описание")
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField()
    style = models.ManyToManyField(style, help_text="Стиль")
    kind = models.CharField(default='Посуда', max_length=200)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('Dish-detail', args=[str(self.id)])

class decor(models.Model):

    title = models.CharField(max_length=200)
    material = models.ForeignKey('Material', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Описание")
    price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField()
    style = models.ManyToManyField(style, help_text="Стиль")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('Decor-detail', args=[str(self.id)])

class author(models.Model):

    nickname = models.CharField(max_length=50)
    about = models.TextField(max_length=200)

    def __str__(self):
        return self.nickname
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    
class article(models.Model):

    title = models.CharField(max_length=200)
    author = models.ManyToManyField(author)
    pub_date = models.DateField()
    text = RichTextField(blank = True, null = True)
    summary = models.TextField(max_length=200)
    theme = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('article-detail', args=[str(self.id)])    

      

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django_filters.views import FilterView
from .filter import potFilter, decorFilter, dishesFilter
# Create your views here.

from .models import size, style, color, material, pot, dishes, decor, author, article, author

def index(request):

    return render(request,'index.html', context={})

def contacts(request):

    return render(
        request,
        'Contacts.html',
        context={})

def about(request):

    return render(
        request,
        'About.html',
        context={})

class potFilterView(FilterView):
    model = pot
    filterset_class = potFilter # ADD YOUR filterset class
        
class decorFilterView(FilterView):
    model = decor
    filterset_class = decorFilter
    
class dishesFilterView(FilterView):
    model = dishes
    filterset_class = dishesFilter

class potDetailView(generic.DetailView):
    model = pot

class decDetailView(generic.DetailView):
    model = decor

class dishDetailView(generic.DetailView):
    model = dishes
    
class articleDetailView(generic.DetailView):
    model = article

class architectureListView(generic.ListView):
    queryset = article.objects.filter(theme = 'Архитектура')
    template_name = 'catalog/architecture.html'

class designListView(generic.ListView):
    queryset = article.objects.filter(theme = 'Дизайн')
    template_name = 'catalog/design.html'

class cultureListView(generic.ListView):
    model = article
    queryset = article.objects.filter(theme = 'Культура')
    template_name = 'catalog/culture.html'

class authorDetailView(generic.DetailView):
    model = author

catalog/templates/About.html
{% extends "base_generic.html" %}

{% block content %}

{% endblock %}

catalog/templates/Contacts.html
{% extends "base_generic.html" %}



{% block content %}
<h class = "headertextstyle"> Позвони, и я скажу: "Здорово, Друг!
    Не забыть бы как тебя зовут!"</h>
    <form>{{ form }}</form>
    {% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% block title %}<title>АрхШум</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
 </head>
 
<body>
	<header class = "headerstyle">
		<p class = "headertextstyle" >АРХШУМ</p>
	</header>

  <ul class="menu-main">
    <li><a href="{% url 'index' %}">Главная</a></li>
    <li><a href="">Статьи</a>
      <ul class="drop-menu">      
        <a href="Architecture.html">Архитектура</a></li>
        <a href="Culture.html">Культура</a></li>
        <a href="Design.html">Дизайн</a></li>
      </ul>
    <li><a href="">Магазин</a>
      <ul class="drop-menu">
        <a href="Pots.html">Горшки</a></li>
        <a href="Dishes.html">Посуда</a></li>
        <a href="Decor.html">декор</a></li>
      </ul>
    <li><a href="url About.html">Обо мне</a></li>
  </ul>
	
 {% block content %}{% endblock %}
     
</body>
</html>

catalog/templates/catalog/Decor_detail.html
{% extends "base_generic.html" %}

{% block content %}



{% endblock %}

catalog/templates/catalog/Decor_filter.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Decor in decor_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Decor.get_absolute_url }}">{{ Decor.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/Dishes_filter.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Dishes in dishes_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Dishes.get_absolute_url }}">{{ Dishes.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/Pot_detail.html
{% extends "base_generic.html" %}

{% block content %}{% endblock %}

catalog/templates/catalog/Pot_filter.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Pot in pot_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Pot.get_absolute_url }}">{{ Pot.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/Pots.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Pot in pot_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Pot.get_absolute_url }}">{{ Pot.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/Soft.html
{% extends "base_generic.html" %}

{% block content %}{% endblock %}

catalog/templates/catalog/culture.html
{% extends "base_generic.html" %}

{% block content %}
    {% for article in article_list %}
        <ul class = 'liststyle'>
            <li>
                <a href="{{ article.get_absolute_url }}">{{ article.title }}</a> 
            </li>
        </ul>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/decor_detail.html
{% extends "base_generic.html" %}

{% block content %}



{% endblock %}

catalog/templates/catalog/decor_filter.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Decor in decor_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Decor.get_absolute_url }}">{{ Decor.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/design.html
{% extends "base_generic.html" %}

{% block content %}
    {% for article in article_list %}
        <ul class = 'liststyle'>
            <li>
                <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
            </li>
        </ul>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/dishes_filter.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Dishes in dishes_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Dishes.get_absolute_url }}">{{ Dishes.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/pot_filter.html
{% extends "base_generic.html" %}

{% block content %} 
<div class = "common">
        <div class = "list">
            {% for Pot in pot_list %}
            <ul class = "liststyle">
                <li>
                <a href="{{ Pot.get_absolute_url }}">{{ Pot.title }}</a> 
            </li>
            </ul>
            {% endfor %}
        </div>
        <div class = "search">
            <form class = "searchform" action="" method="get">
                {{ filter.form.as_p }}
                <input type="submit" value="Искать"/>
            </form>
        </div>
{% endblock %}

catalog/templates/catalog/rishes_detail.html
{% extends "base_generic.html" %}

{% block content %}{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}


{% endblock %}